# create an environment in which notebooks in this directory can be run with:
#
#  conda env create -f environment.yaml
#  pip install -e ../../../tools/SalishSeaTools/

name: sog-waves-analysis

channels:
  - defaults
  - gomss-nowcast
  - conda-forge

dependencies:
  - bottleneck
  - cmocean
  - hdf4
  - jupyter_contrib_nbextensions
  - matplotlib
  - netCDF4
  - notebook
  - pip
  - python=3.6
  - requests
  - scipy
  - xarray
  - pip:
      - angles
      - arrow
      - retrying
      - yapf
