# conda environment description file for generic analysis work
#
#    $ conda env create -f environment.yaml
#    $ conda activate analysis-doug

name: analysis-doug

channels:
  - conda-forge
  - nodefaults

dependencies:
  - arrow
  - black
  - bottleneck
  - cftime
  - cmocean
  - jupyterlab
  - matplotlib
  - nc-time-axis
  - netCDF4
  - pip
  - python=3.10
  - xarray
