# conda environment description file for preparation and exploration of
# SalishSeaCast_hourly_prod NEMO configuration created in Apr-2025.
#
# The config is for runs of a version of SalishSeaCast v202111 modified by Tall
# for collaboration with Sacchi to compare model results with observation from 22-27
# August 2024 near the northwest end of Texada Island.
#
#    $ mamba env create -f environment.yaml
#    $ mamba activate SalishSeaCast_hourly_prod

name: SalishSeaCast_hourly_prod

channels:
  - conda-forge
  - nodefaults

dependencies:
  - arrow
  - cmocean
  - h5netcdf
  - matplotlib
  - notebook
  - python=3.13
  - xarray
