# conda environment description file for experiments with dask on
# SalishSeaCast NEMO results files
#
#    $ conda env create -f environment.yaml
#    $ source activate dask-expts
#    (dask-expts)$ jupyter labextension install @jupyterlab/toc
#    (dask-expts)$ jupyter labextension install @ryantam626/jupyterlab_code_formatter
#    (dask-expts)$ jupyter serverextension enable --py jupyterlab_code_formatter

name: dask-expts

channels:
  - conda-forge
  - defaults

dependencies:
  - dask
  - jupyterlab
  - matplotlib
  - netCDF4
  - numpy
  - pandas
  - python=3.8
  - xarray

  # for jupyterlab extensions
  - nodejs

  # code formatting
  - jupyterlab_code_formatter
