# conda environment description file for experiments with dask on
# SalishSeaCast NEMO results files
#
#    $ conda env create -f environment.yaml
#    $ source activate dask-expts
#    (dask-expts)$ jupyter labextension install @jupyterlab/toc
#    (dask-expts)$ python3 -m pip install -e ../tools/SalishSeaTools/

name: dask-expts

channels:
  - conda-forge
  - defaults

dependencies:
  - arrow
  - basemap
  - bottleneck
  - cliff
  - cmocean
  - dask
  - gsw
  - jupyterlab
  - matplotlib
  - netCDF4
  - numpy
  - pandas
  - pip
  - progressbar
  - python=3.8
  - python-graphviz
  - pytz
  - requests
  - retrying
  - scipy
  - xarray

  # for jupyterlab extensions
  - nodejs

  - pip:
      - angles
