# conda environment description file for experiments with dask on
# SalishSeaCast NEMO results files
#
#    $ conda env create -f environment.yaml
#    $ source activate dask-expts
#    (dask-expts)$ jupyter labextension install @jupyterlab/toc

name: dask-expts

channels:
  - conda-forge
  - defaults

dependencies:
  - arrow
  - dask
  - jupyterlab
  - matplotlib
  - netCDF4
  - numpy
  - pandas
  - python=3.8
  - python-graphviz
  - xarray

  # for jupyterlab extensions
  - nodejs
