# conda environment description file for experiments with dask on
# SalishSeaCast NEMO results files
#
#    $ conda env create -f environment.yaml
#    $ conda activate dask-expts
#    (dask-expts)$ python3 -m pip install -e ../tools/SalishSeaTools/

name: dask-expts

channels:
  - conda-forge
  - nodefaults

dependencies:
  - arrow
  - black
  - bottleneck
  - cliff
  - cmocean
  - dask
  - gsw
  - jupyterlab
  - matplotlib
  - netCDF4
  - pip
  - python=3.10
  - python-graphviz
  - pytz
  - scipy
  - xarray

  - pip:
      - angles
