name: onc-api

channels:
  - conda-forge
  - defaults

dependencies:
  - cmocean
  - jupyter_contrib_nbextensions
  - matplotlib
  - notebook
  - pip
  - python
  - xarray

  - pip:
    - onc
    - yapf
