# conda environment description file for preparation and exploration of
# SalishSeaCast v202111 double resolution experiment in mid-2024
#
#    $ conda env create -f environment.yaml
#    $ conda activate 2xrez-202111

name: 2xrez-202111

channels:
  - conda-forge
  - nodefaults

dependencies:
  - arrow
  - black
  - bottleneck
  - cmocean
  - h5netcdf
  - jupyterlab
  - matplotlib
  - notebook
  - python=3.12
  - scipy
  - xarray
