# conda environment description file for hindcast-dayavgs tool
#
# Create a conda environment in which you can run the code in this dir with:
#
#   $ conda env create -f environment.yaml
#   $ conda activate hindcast-dayavgs

name: hindcast-dayavgs

channels:
  - conda-forge

dependencies:
  - arrow
  - bottleneck
  - dask
  - netCDF4
  - python>=3.8
  - xarray

  # For interactive development
  - jupyterlab

  # Temporary work-around for ipython imcompatibility w/ jedi
  # that breaks tab completion
  - jedi<0.18.0

  # For verification plots
  - cmocean
  - matplotlib
